server:
  port: 8081
  context-path: /wxmanage
logging:
  level:
    org.springframework.web: debug
    com.bon.mapper: warn

wechat:
  mp:
    appId: wx74076d787edd4ab7
    secret: d4624c36b6795d1d99dcf0547af5443d
    token: 7789d33e412a42eb95899141ceb68293
    aesKey: 123

spring:
  datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/wxmanage?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: 12345678
        # 初始化大小，最小，最大
        initialSize: 5
        minIdle: 5
        maxIdle: 100
        maxActive: 200
        # 配置获取连接等待超时的时间
        maxWait: 5000
        # 每次使用连接时进行校验，会影响系统性能。默认为false
        testOnBorrow: false
        # 验证使用的SQL语句
        validationQuery: SELECT 1
        # 指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除
        testWhileIdle: true
        # 每30秒运行一次空闲连接回收器（默认-1）
        timeBetweenEvictionRunsMillis: 30000
        # 池中的连接空闲30分钟后被回收（默认30分钟）
        minEvictableIdleTimeMillis: 1800000
        # 在每次空闲连接回收器线程(如果有)运行时检查的连接数量（设置为和maxIdle一样）
        numTestsPerEvictionRun: 100
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        #合并多个DruidDataSource的监控数据
        useGlobalDataSourceStat: true

#  thymeleaf:
#    cache: false
#    prefix: classpath:/templates/
#    mode: LEGACYHTML5
## redis
#  redis:
#    database: 0       # Redis数据库索引（默认为0）
#    host: 192.168.0.189
#    port: 6379
##    password:
##    timeout:
#    pool:
#      max-active: 12   # 连接池最大连接数（使用负值表示没有限制）
#      max-wait: -1     # 连接池最大阻塞等待时间（使用负值表示没有限制）
#      max-idle: 4      # 连接池中的最大空闲连接
#      min-idle: 1      # 连接池中的最小空闲连接

# # mongo
#  data:
#    mongodb:
#      database:
#      host:
#      port:
#      username:
#      password:

mybatis:
  type-aliases-package: com.bon.entity
  mapper-locations: classpath*:/mybaits/*Mapper.xml

mapper:
    mappers:
    - com.bon.util.MyMapper
    not-empty: false
    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql


